version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: planner_casamento_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - planner_casamento_pgdata:/var/lib/postgresql/data

volumes:
  planner_casamento_pgdata:
    driver: local

